### ISSUE TITLE
Publish on maven repository central

### ISSUE THREAD

**Issue by RNiveau** [bodar/totallylazy#1]
Hi,

I would like tu use cucumber report for my project.
This plugin use totallylazy as dependency.

Totallylazy is not available in maven repository central.

I'm in a company which doesn't allow to download dependency from another repository and I can't push the jar manually in nexus.

Can you deploy your project on maven repository central ?

Thanks.

**Comment by pniederw** [comment]
How about publishing to https://bintray.com?. Not publishing to either Bintray or Maven Central will make the library unnecessarily hard to use for many people.
