### ISSUE TITLE
Remove these methods from Option to enforce passing a callable for laziness

### ISSUE THREAD

**Issue by daviddenton** [bodar/totallylazy#17]
public abstract Option<A> orElse(Option<A> other);
    public abstract A getOrElse(A other);

**Comment by danielbodart** [comment]
Okay I've looked into this more and this really seems to only be a surprise if you come from Scala. 

I literally have hundreds of usages using primitives or empty values i.e 0, "", list() and I wouldn't want these to have the the visual noise of a lambda or the performance impact.

Let me know what you think
