### ISSUE TITLE
result of repeat(callable).take(x) is constantly changing

### ISSUE THREAD

**Issue by takaczapka** [bodar/totallylazy#27]
Below test will fail.

```
    @Test
    public void testRepeatTake() {
        Sequence<Integer> seq = repeat(() -> Randoms.integers().head()).take(5);
        assertThat(seq, is(seq));
    }
```

It's due to the fact that
/com/googlecode/totallylazy/Sequences.java:438 .. take(...) 
is not evaluated eagerly and relies on values from (ever changing) RepeatIterator. 

Possible solution would be to eagerly take elements (that's what Scala does on Seq.take(x)):
```
    public static <T> Sequence<T> take(final Iterable<? extends T> iterable, final int count) {
        List<T> ts = Iterators.toList(Iterators.take(iterable.iterator(), count));
        return new Sequence<T>() {
            public final Iterator<T> iterator() {
                return ts.iterator();
            }
        };
    }
```

Some of other functions affected: takeWhile, drop and dropWhile.

**Comment by danielbodart** [comment]
If you want the same results your should call memorise/memoize, totallylazy is about lazyness where ever possible;)
