### ISSUE TITLE
Setting up Maven Bodar as a remote repository breaks Artifactory

### ISSUE THREAD

**Issue by mikeycmccarthy** [bodar/totallylazy#31]
We setup http://repo.bodar.com as a remote in Artifactory in order to pull through the totallylazy libraries. A few weeks ago we noticed that every Artifactory virtual repo that included Bodar as a remote was breaking. Finally narrowed the issue down to Bodar...even setting it up as a remote causes Artifactory to spew out an error when you navigate to it directly.

The error looks like this:

```
{
  "errors" : [ {
    "status" : 404,
    "message" : "{\"error\":\"Error on line 27: The reference to entity \\\"prefix\\\" must end with the ';' delimiter.\"}"
  } ]
}
```

Did something recently change in the way that the Bodar repo presents its metadata? I guess Artifactory must be consuming something it doesn't expect or like?

**Comment by danielbodart** [comment]
Nothing has changed on repo.bodar.com, however thanks to @jshiell we now have the very latest version pushing to bin tray : https://bintray.com/bodar/maven/totallylazy/2.286

**Comment by mikeycmccarthy** [comment]
Nice, thank you @jshiell (and thanks @danielbodart for letting me know). I'll let the teams that use the dependency know so they can upgrade and get this version. We've done an Artifactory upgrade our end so maybe the issue is with Artifactory here.
